services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\RPDBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\RPDBundle\Decorator\ProfileController:
        decorates: App\Controller\ProfileController

    KimaiPlugin\RPDBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']